---
title: "First Blog Post"
description: |
  A short description of the post.
author:
  - name: Stephanie Gluck
    url: https://github.com/s-gluck
date: 02-24-2020
categories: 
  - dataviz 
  - class
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

theme_set(theme_minimal(15))

```

Here is an example page for my first new post 

I'm going to create a plot and display it in different ways. 

```{r plot-ex}


ggplot(mpg, aes(displ, cty)) + 
  geom_point() + 
  geom_smooth() +
  labs(title = "Default plot rendering")

```

Plot with body outset - allows the plot to be further out than previous plot contained in the column 

```{r plot-ex2, layout = "l-body-outset"}


ggplot(mpg, aes(displ, cty)) + 
  geom_point() + 
  geom_smooth() +
  labs(title = "body outset")

```

```{r plot-ex3, layout = "l-page"}


ggplot(mpg, aes(displ, cty)) + 
  geom_point() + 
  geom_smooth() +
  labs(title = "page layout")

```

loyout screen 

```{r plot-ex4, layout = "l-screen"}


ggplot(mpg, aes(displ, cty)) + 
  geom_point() + 
  geom_smooth() +
  labs(title = "screen layout")

```

Side note shows up below rather than to the side of the plot becaues it is so big 

<aside>

This plot over here is huge! 

</aside>


<aside>

```{r aside-table, echo = F}

mpg %>% 
  head() %>% 
  select(manufacturer, model, displ, cty) %>% 
  gt::gt()

```

</aside>



```{r aside-table-full, layout = "l-page"}

mpg %>% 
  reactable::reactable()
```